### PR TITLE
feat: adds check in dao creation for exec permission

### PR DESCRIPTION
**Pull request by mathewmeconry**
## Description

Adds a check during `createDao()` if at least one plugin gets `EXECUTE_PERMISSION`

Task: APP-1200

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder of the package after the [UPCOMING] title and before the latest version.
- [ ] I have tested my code on the test network.

### CODE REVIEW

**Review by josemarinas — COMMENTED** [review]
Looks good to me, please fix the `deno` formatting and the conflicts with the main branch, and I think we are good to go

**Comment by mathewmeconry** [comment]
> Looks good to me, please fix the `deno` formatting and the conflicts with the main branch, and I think we are good to go

done

**Review by brickpop — APPROVED** [review]
Changes look good, thank you!

**Comment by brickpop** [comment]
Can you rebase the changes and bump the NPM version @mathewmeconry ?

**Comment by mathewmeconry** [comment]
> Can you rebase the changes and bump the NPM version @mathewmeconry ?

done

**Review by josemarinas — APPROVED** [review]

**Pull request merged**
